a=float(input("Enter the value of a: "))
b=float(input("Enter the value of b: "))
c=float(input("Enter the value of c: "))
x=(-b+((b**2)-4*a*c)**0.5)/(2*a)
y=(-b-((b**2)-4*a*c)**0.5)/(2*a)
print(x)
print(y)
